package entity;

public interface MessageType {
	//operation
	String LOGIN = "LOGIN";
	String REGISTER = "REGISTER";
	String MYFRIEND = "MYFRIEND";
	String SECONDQUERY = "SECONDQUERY";
	String ORDER_REFRESH = "ORDER_REFRESH";
	String NEW_FRIENDS = "NEW_FRIENDS";
	String SET_AVATAR = "SET_AVATAR";
	String PUBLISH = "PUBLISH";
	String RECEIVE = "RECEIVE";
	String ORDERPUBLISH="ORDERPUBLISH";
	String CHANGEPW="CHANGEPW";
	String PW_WRONG="PW_WRONG";
	String ADDFRIEND = "ADDFRIEND";
	String ADDFRIENDIF = "ADDFRIENDIF";
	String SENDMESSAGE = "SENDMESSAGE";
	String CONFIRM = "CONFIRM";
	String LOAD_CHAT_RECORDS = "LOAD_CHAT_RECORDS"; //加载聊天记录
	String FINDPASSWORD="FINDPASSWORD";
	String RANKING="RANKING";
	String ADDPOINT="ADDPOINT";
	//success or failure
	String LOGIN_SUCCESS = "LOGIN_SUCCESS";
	String LOGIN_FAILURE = "LOGIN_FAILURE";
	String ORDER_REFRESH_SUCCESS = "ORDER_REFRESH_SUCCESS";
	String ORDER_REFRESH_FAILURE = "ORDER_REFRESH_FAILURE";
	String SET_AVATAR_SUCCESS = "SET_AVATAR_SUCCRSS";
	String SET_AVATAR_FAILURE = "SET_AVATAR_FAILURE";
	String ORDERPUBLISH_SUCCESS="ORDERPUBLISH_SUCCESS";
	String ORDERPUBLISH_FAILURE="ORDERPUBLISH_FAILURE";
	String FINDPASSWORD_SUCCESS="FINDPASSWORD_SUCCESS";
	String FINDPASSWORD_FAILURE="FINDPASSWORD_FAILURE";
	
	String REGISTER_1 = "1";
	String REGISTER_2 = "2";
	String REGISTER_3 = "3";
	String CHANGEPW_SUCCESS="CHANGEPW_SUCCESS";
	String CHANGEPW_FAILURE="CHANGEPW_FAILURE";
	//data
	
	String LOAD_CHAT_RECORDS_SUCCESS = "LOAD_CHAT_RECORDS_SUCCESS";  //加载聊天记录成功
	String LOAD_CHAT_RECORDS_FAILURE = "LOAD_CHAT_RECORDS_FAILURE";  //加载聊天记录失败
	 
	String CHAT_RECEIVED = "CHAT_RECEIVED";  //接收的聊天消息
	String CHAT_SENT = "CHAT_SENT";  //发送的聊天消息
	String UPDATE_CHAT_RECORDS = "UPDATE_CHAT_RECORDS";  //更新聊天消息
	String NEW_CHAT_RECORD = "NEW_CHAT_RECORD";  //服务器转发的聊天消息
	String ORIGNAL_CHAT_RECORD = "ORIGNAL_CHAT_RECORD"; //未转发的聊天消息
	//data
	String INSERT_CHAT_RECORDS = "INSERT_CHAT_RECORDS";  //将消息插入数据库
	String INSERT_CHAT_RECORDS_SUCCESS = "INSERT_CHAT_RECORDS_SUCCESS";  //将消息插入数据库成功
	String INSERT_CHAT_RECORDS_FAILURE = "INSERT_CHAT_RECORDS_FAILURE";  //将消息插入数据库失败
	String SENT_CHART = "SENT_CHART";
	String CHATER_REFRESH = "CHATER_REFRESH";
	String FIND_USER = "FIND_USER";
}
